// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function FetchCancel(arg1) {
  return window['go']['main']['App']['FetchCancel'](arg1);
}

export function FetchStart(arg1) {
  return window['go']['main']['App']['FetchStart'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SettingsPath() {
  return window['go']['main']['App']['SettingsPath']();
}
