// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function FetchCancel(arg1:string):Promise<void>;

export function FetchStart(arg1:main.FetchRequest):Promise<main.FetchHead>;

export function GetSettings():Promise<main.Settings>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SettingsPath():Promise<string>;
