// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function All():Promise<Record<string, string>>;

export function Path():Promise<string>;

export function Set(arg1:string,arg2:string):Promise<void>;
