// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function All() {
  return window['go']['main']['KV']['All']();
}

export function Path() {
  return window['go']['main']['KV']['Path']();
}

export function Set(arg1, arg2) {
  return window['go']['main']['KV']['Set'](arg1, arg2);
}
