// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDocument(arg1:main.Document):Promise<number>;

export function AddFolder(arg1:main.Folder):Promise<number>;

export function AddSnapshot(arg1:main.Snapshot):Promise<number>;

export function AddSnippet(arg1:main.Snippet):Promise<number>;

export function ClearSnapshots(arg1:number):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function DeleteFolder(arg1:number):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function GetDocument(arg1:number):Promise<main.Document>;

export function GetSnapshot(arg1:number,arg2:number):Promise<main.Snapshot>;

export function ListDocuments():Promise<Array<main.Document>>;

export function ListFolders():Promise<Array<main.Folder>>;

export function ListSnapshots(arg1:number):Promise<Array<main.Snapshot>>;

export function ListSnippets():Promise<Array<main.Snippet>>;

export function RenameFolder(arg1:number,arg2:string):Promise<void>;

export function Root():Promise<string>;

export function UpdateDocument(arg1:number,arg2:main.DocumentPatch):Promise<void>;
