// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocument(arg1) {
  return window['go']['main']['Store']['AddDocument'](arg1);
}

export function AddFolder(arg1) {
  return window['go']['main']['Store']['AddFolder'](arg1);
}

export function AddSnapshot(arg1) {
  return window['go']['main']['Store']['AddSnapshot'](arg1);
}

export function AddSnippet(arg1) {
  return window['go']['main']['Store']['AddSnippet'](arg1);
}

export function ClearSnapshots(arg1) {
  return window['go']['main']['Store']['ClearSnapshots'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['Store']['DeleteDocument'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['Store']['DeleteFolder'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['Store']['DeleteSnippet'](arg1);
}

export function GetDocument(arg1) {
  return window['go']['main']['Store']['GetDocument'](arg1);
}

export function GetSnapshot(arg1, arg2) {
  return window['go']['main']['Store']['GetSnapshot'](arg1, arg2);
}

export function ListDocuments() {
  return window['go']['main']['Store']['ListDocuments']();
}

export function ListFolders() {
  return window['go']['main']['Store']['ListFolders']();
}

export function ListSnapshots(arg1) {
  return window['go']['main']['Store']['ListSnapshots'](arg1);
}

export function ListSnippets() {
  return window['go']['main']['Store']['ListSnippets']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['Store']['RenameFolder'](arg1, arg2);
}

export function Root() {
  return window['go']['main']['Store']['Root']();
}

export function UpdateDocument(arg1, arg2) {
  return window['go']['main']['Store']['UpdateDocument'](arg1, arg2);
}
